import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const files=['products.js','commerce-config.js','cart-store.js','demo-payment.js'];
const modules={};
for(const file of files){let source=await readFile(new URL('../dist/'+file,import.meta.url),'utf8');for(const [name,url] of Object.entries(modules))source=source.replaceAll(`'./${name}'`,JSON.stringify(url));modules[file]='data:text/javascript;base64,'+Buffer.from(source).toString('base64');}
const {readCart,writeCart,putItem,normalizeCart,totals}=await import(modules['cart-store.js']);
const {createDemoOrder,approveDemo,renewDemo,paymentStatus,demoPixCode}=await import(modules['demo-payment.js']);
const {COMMERCE}=await import(modules['commerce-config.js']);
let encoded=null;const storage={getItem:()=>encoded,setItem:(key,value)=>{encoded=value;}};
let cart=putItem([],'borboletoscopio',{body:'pink',details:'blue'});
cart[0].quantity=2;const firstId=cart[0].id;
writeCart(cart,storage);assert.deepEqual(readCart(storage),cart,'reload retains selection and quantity');
cart=putItem(cart,'borboletoscopio',{body:'pink',details:'blue'});
assert.equal(cart.length,1);assert.equal(cart[0].quantity,3,'same selection merges intentionally');
cart=putItem(cart,'borboletoscopio',{body:'mint',details:'yellow'});
assert.equal(cart.length,2,'different selections remain distinct');
cart=putItem(cart,'borboletoscopio',{body:'mint',details:'yellow'},null,firstId);
assert.equal(cart.length,1);assert.equal(cart[0].quantity,4,'editing into another configuration merges without losing quantity');
assert.throws(()=>putItem(cart,'borboletoscopio',{},null,'removed-id'));
for(const productId of ['dinossauroscopio','aviaoscopia'])cart=putItem(cart,productId,{body:'lilac',details:'pink',engines:'white'});
assert.equal(cart.at(-1).selection.engines,'white');
assert.equal(totals(cart).total,4*12900+13900+15900+1800);
assert.deepEqual(totals([]),{subtotal:0,shipping:0,total:0});
const corrupt=normalizeCart([{productId:'__proto__'},{productId:'missing'},null,{productId:'aviaoscopia',quantity:-3,selection:{body:'invalid'},unitPrice:1,thumbnail:'https://untrusted.invalid/a.png'}]);
assert.equal(corrupt.length,1);assert.equal(corrupt[0].quantity,1);assert.equal(corrupt[0].unitPrice,15900);assert.equal(corrupt[0].selection.body,'blue');assert.equal(corrupt[0].thumbnail,null);
encoded='broken';assert.deepEqual(readCart(storage),[]);
assert.throws(()=>writeCart(cart,{setItem(){throw Error('QuotaExceeded');}}),/salvar/);
assert.throws(()=>createDemoOrder([],'pix'));assert.throws(()=>createDemoOrder(cart,'invalid'));
const now=100000, order=createDemoOrder(cart,'pix',now),originalQuantity=order.items[0].quantity;
cart[0].quantity=1;assert.equal(order.items[0].quantity,originalQuantity,'order is an immutable snapshot of cart');
assert.equal(paymentStatus(order,now),'pending');
assert.equal(paymentStatus(order,now+COMMERCE.pixDurationMs),'expired');
assert.throws(()=>approveDemo(order,now+COMMERCE.pixDurationMs));
const renewed=renewDemo(order,now+COMMERCE.pixDurationMs+1);
assert.notEqual(demoPixCode(order),demoPixCode(renewed));assert.equal(renewed.id,order.id);assert.equal(renewed.attempt,2);
assert.equal(paymentStatus(renewed,renewed.expiresAt-1),'pending');
const paid=approveDemo(renewed,renewed.expiresAt-1);assert.equal(paymentStatus(paid,renewed.expiresAt+10000),'approved');assert.throws(()=>approveDemo(paid));assert.throws(()=>renewDemo(paid));
assert.throws(()=>approveDemo({...order,mode:'live'},now),'demo adapter refuses live approval');
const card=createDemoOrder(cart,'card',now);assert.equal(paymentStatus(card,now+COMMERCE.pixDurationMs),'pending');assert.equal(approveDemo(card).status,'approved');
console.log('PASS: cart persistence, all product color maps, merge/edit/quantity/totals, hostile storage, storage failure, order snapshot, Pix expiration/renewal/approval, card approval and live-mode refusal.');
