import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const classes=new Set(),listeners=new Map(),frames=new Map();let id=0;
globalThis.scrollY=0;
globalThis.requestAnimationFrame=fn=>{frames.set(++id,fn);return id;};
globalThis.cancelAnimationFrame=key=>frames.delete(key);
const tick=()=>{const pending=[...frames.values()];frames.clear();pending.forEach(fn=>fn());};
globalThis.window={addEventListener:(name,fn)=>listeners.set(name,fn)};
const spacer={style:{},setAttribute(){}};
globalThis.document={createElement:()=>spacer,activeElement:null,addEventListener(){}};
const header={offsetHeight:94,classList:{add:c=>classes.add(c),remove:c=>classes.delete(c),toggle:(c,on)=>on?classes.add(c):classes.delete(c)},after(){},contains:()=>false,querySelector:()=>null,toggleAttribute(){}};
const code=await readFile(new URL('../dist/header-scroll.js',import.meta.url),'utf8');
const {setupScrollHeader}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
setupScrollHeader(header);
const scroll=y=>{globalThis.scrollY=y;listeners.get('scroll')();tick();};
scroll(60); assert.equal(classes.has('is-floating'),false);
scroll(100);
assert.equal(classes.has('is-floating'),true);
assert.equal(classes.has('is-revealed'),false,'descending header stays hidden');
assert.equal(classes.has('is-positioning'),true,'flow-to-fixed change has no slide transition');
assert.equal(spacer.style.height,'94px','content keeps its original position');
tick(); assert.equal(classes.has('is-positioning'),true,'guard survives the first paint');
tick(); assert.equal(classes.has('is-positioning'),false,'normal transitions resume');
scroll(180);scroll(150);
assert.equal(classes.has('is-revealed'),true,'upward scrolling reveals compact header');
assert.equal(classes.has('is-positioning'),false,'reveal keeps its smooth transition');
scroll(190);assert.equal(classes.has('is-revealed'),false);
scroll(0);assert.equal(classes.has('is-floating'),false);
assert.equal(classes.has('is-positioning'),true,'return to document flow is also atomic');
assert.equal(classes.has('has-scrolled'),true,'intro animation cannot replay on returning to top');
assert.equal(spacer.style.height,'0px');
tick();tick();
scroll(120);scroll(0);tick();tick();
assert.equal(classes.has('is-positioning'),false,'rapid direction changes release the temporary guard');
console.log('PASS: no-transition flow/fixed handoff, scroll direction, stable spacer, top return and rapid reversal.');
